# Generated by Django 5.2.5 on 2025-09-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_id_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Id_Organization',
            new_name='Organization',
        ),
    ]
